# docker-compose.windows.yml
version: '3'

services:
  instance-manager:
    volumes:
      - type: bind
        source: //var/run/docker.sock
        target: //var/run/docker.sock
        bind:
          create_host_path: true
