version: '3'

services:
  szoftarch-db:
    image: mysql:8.0
    container_name: szoftarch-db
    environment:
      MYSQL_ROOT_PASSWORD: david
      MYSQL_DATABASE: plant_care
      MYSQL_USER: user
      MYSQL_PASSWORD: teszt
    ports:
      - "3306:3306"
    networks:
      szoftarch-nw:
        aliases:
          - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pdavid"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./szoftarch.backend
    image: backend:latest
    ports:
      - "5000:5000"
    networks:
      szoftarch-nw:
        aliases:
          - szoftarch-db
    depends_on:
      szoftarch-db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://szoftarch-db:3306/plant_care
      DB_USER: user
      DB_PASSWORD: teszt

  device-validator:
    build:
      context: ./iotdevices
      dockerfile: ./Dockerfile.validator
    image: validator
    ports:
      - "5001:5001"
    networks:
      szoftarch-nw:
        aliases:
          - "szoftarch-validator"
    depends_on:
      szoftarch-db:
        condition: service_healthy
        
  instance-manager:
    build:
      context: ./iotdevices
      dockerfile: ./Dockerfile.instance-manager
    image: instance-manager:latest
    ports:
      - "5002:5002"
    networks:
      szoftarch-nw:
    depends_on:
      szoftarch-db:
        condition: service_healthy
    environment:
      DB_HOST: szoftarch-db
      DB_PORT: 3306
      DB_NAME: plant_care
      DB_USER: user
      DB_PASSWORD: teszt
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: true
    # Override the socket path for Windows if needed
    profiles:
      - linux
      - windows

networks:
  szoftarch-nw:
    driver: bridge
