spring:
  application:
    name: szoftarch.backend

  datasource:
    url: jdbc:mysql://szoftarch-db:3306/plant_care   # Az adatbázis URL-je
    username: user                                # Az adatbázis felhasználója
    password: teszt                               # Az adatbázis jelszava
    driver-class-name: com.mysql.cj.jdbc.Driver  # A MySQL JDBC driver osztálya

  jpa:
    hibernate:
      ddl-auto: update                           # Automatikusan frissíti a sémát (az első indításkor)
    show-sql: true                               # SQL lekérdezések naplózása
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL8 dialect
server:
  port: 5000

custom:
  external-service:
    address: 'dns:///hm-backend:5000'
