FROM python:3.9-slim

WORKDIR /app

# Copy requirements first to leverage Docker cache
COPY requirements-actuator.txt .
RUN pip install --no-cache-dir -r requirements-actuator.txt

# Copy the application
COPY actuator_api.py .

# Environment variables for MySQL connection
ENV DB_HOST=szoftarch-db
ENV DB_USER=user
ENV DB_PASSWORD=teszt
ENV DB_NAME=plant_care
ENV DB_PORT=3306

EXPOSE 5001

# Command to run the API
ENTRYPOINT ["uvicorn", "actuator_api:app", "--host", "0.0.0.0", "--port", "5003"]
